name: Test

on:
  workflow_call

jobs:
  test-min:
    name: Min
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, '3.10']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Download wheel artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/

      - name: Get wheel file name
        uses: tj-actions/glob@v10
        id: glob
        with:
          files: dist/galois-*.whl

      - name: Install minimum package dependencies
        run: python3 -m pip install -r requirements-min.txt

      - name: Install the `galois` package wheel with [dev]
        run: python3 -m pip install ${{ steps.glob.outputs.paths }}[dev]

      - name: Test with pytest
        run: python3 -m pytest tests/ --cov=src/galois/ --cov-report=xml tests/

      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false
          verbose: true

  test-latest:
    name: Latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, '3.10']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Download wheel artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/

      - name: Get wheel file name
        uses: tj-actions/glob@v10
        id: glob
        with:
          files: dist/galois-*.whl

      - name: Install the `galois` package wheel with [dev]
        run: python3 -m pip install --upgrade ${{ steps.glob.outputs.paths }}[dev]

      - name: Test with pytest
        run: python3 -m pytest tests/ --cov=src/galois/ --cov-report=xml tests/

      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false
          verbose: true
